STOP_WORDS = set(['its', 'whence', 'enough', 'again', 'by', 'don', 'hereby',
        'formerly', 'mostly', 'wherein', 'himself', 'to', 'amoungst', 't', 'had',
        'something', 'these', 'those', 'doing', 'un', 'whatever', 'latter', 'he',
        'per', 'have', 'whereupon', 'keep', 'the', 'nowhere', 'afterwards', 'there',
        'herself', 'behind', 'even', 'except', 'whereas', 'yet', 'whenever', 'always',
        'along', 'same', 'several', 'or', 'nobody', 'empty', 'in', 'via', 'hence',
        'who', 'against', 'so', 'their', 'over', 'am', 're', 'con', 'onto', 'where',
        'here', 'nor', 'somehow', 'ever', 'never', 'someone', 'somewhere', 'since',
        'without', 'before', 'of', 'anything', 'which', 'another', 'herein', 'least',
        'anyway', 'at', 'perhaps', 'this', 'among', 'often', 'amongst', 'about', 'such',
        'any', 'seeming', 'couldnt', 'out', 'more', 'll', 'one', 'thin', 'will',
        'yourself', 'for', 'however', 'everyone', 'therein', 'doesn', 'because', 'as',
        'might', 've', 'whither', 'are', 'themselves', 'y', 'down', 'de', 'everything',
        'would', 'much', 'mine', 'what', 'co', 'therefore', 'becoming', 'your', 'him',
        'take', 'she', 'may', 'under', 'due', 'myself', 'both', 'etc', 'hers', 'm',
        'thence', 'seem', 'until', 'a', 'from', 'yours', 'through', 'now', 'ours',
        'nevertheless', 'sincere', 'once', 'than', 'during', 'it', 'amount', 'having',
        'noone', 'elsewhere', 'must', 'toward', 'all', 's', 'beforehand', 'others',
        'between', 'hasnt', 'that', 'does', 'too', 'being', 'well', 'get', 'only',
        'indeed', 'less', 'anyone', 'seems', 'becomes', 'some', 'own', 'upon',
        'with', 'put', 'me', 'hereupon', 'although', 'how', 'either', 'together',
        'done', 'back', 'none', 'each', 'off', 'when', 'do', 'can', 'is', 'thereafter',
        'cannot', 'on', 'become', 'most', 'already', 'please', 'beside', 'should',
        'ma', 'rather', 'moreover', 'towards', 'her', 'also', 'whoever', 'you', 'has',
        'whose', 'else', 'whether', 'many', 'o', 'within', 'been', 'nothing', 'sometime',
        'was', 'hereafter', 'meanwhile', 'otherwise', 'i', 'after', 'around', 'up',
        'whereafter', 'below', 'everywhere', 'didn', 'my', 'further', 'them', 'top',
        'latterly', 'still', 'go', 'thus', 'just', 'and', 'while', 'almost', 'could',
        'wherever', 'but', 'across', 'above', 'his', 'neither', 'sometimes', 'be',
        'alone', 'why', 'our', 'side', 'us', 'ourselves', 'whom', 'they', 'theirs',
        'anyhow', 'd', 'very', 'whereby', 'no', 'serious', 'seemed', 'then', 'thereby',
        'if', 'few', 'were', 'throughout', 'thru', 'every', 'though', 'beyond', 'ie',
        'other', 'anywhere', 'part', 'did', 'yourselves', 'besides', 'namely', 'not',
        'thereupon', 'cant', 'into', 'itself', 'an', 'we', 'eg', 'nt', "n't", "'m",
        "'s", "'ve", 'ca', "would've", 'wouldve', "ya'll", 'yall'])
